
exclude:
  - readme.md
  - .github/
header_pages:
  - header1.html
author: Tyler Farmer, Esquire
twitter_username: none
github_username:  Tylerfarmer1
plugins:
  - jekyll-sitemap
  - jekyll-mentions
  - jemoji
markdown: kramdown
kramdown:
   syntax_highlighter_opts:
      disable : true
