remote_theme: pages-themes/cayman@v0.2.0
# remote_theme: pages-themes/dinky@v0.2.0
#remote_theme: MicrosoftLearning/Jekyll-Theme
exclude:
  - readme.md
  - .github/
#header_pages:
#  - header1.html
author: Tyler Farmer
plugins:
  - jekyll-sitemap
  - jekyll-mentions
  - jemoji
  - jekyll-remote-theme # add this line to the plugins list if you already have one
markdown: kramdown
kramdown:
   syntax_highlighter_opts:
      disable : true
